SELECT CITY,LENGTH(CITY) AS LENCITY FROM STATION
GROUP BY CITY
ORDER BY LENGTH(CITY),CITY ASC
LIMIT 1;

SELECT CITY,LENGTH(CITY) AS LENCITY FROM STATION
GROUP BY CITY
ORDER BY LENGTH(CITY) DESC,CITY ASC
LIMIT 1;
